--1
SELECT PD.EMP_LNAME, SUM(CHAR_DISTANCE) AS [DISTANCE]
FROM PILOTDIM PD INNER JOIN FACT F ON PD.PILOT_ID = F.PILOT_ID
GROUP BY F.PILOT_ID, PD.EMP_LNAME
HAVING SUM(CHAR_DISTANCE) = (
SELECT TOP 1 SUM(CHAR_DISTANCE) 
FROM PILOTDIM PD INNER JOIN FACT F ON PD.PILOT_ID = F.PILOT_ID
GROUP BY F.PILOT_ID, PD.EMP_LNAME
ORDER BY SUM(CHAR_DISTANCE) DESC)	
	

--2
SELECT PD.EMP_LNAME, T.CHAR_DATE, SUM(REVENUE) AS [REVENUE]
FROM PILOTDIM PD INNER JOIN FACT F ON PD.PILOT_ID = F.PILOT_ID
				INNER JOIN TIMEDIM T ON F.TIME_ID= T.TIME_ID
GROUP BY F.PILOT_ID, F.TIME_ID, PD.EMP_LNAME, T.CHAR_DATE						