
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE A10P3  
AS
BEGIN
	
	ALTER TABLE FACT
	DROP CONSTRAINT FK_FACT_TIMEDIM, FK_FACT_MODELDIM, FK_FACT_PILOTDIM

	TRUNCATE TABLE FACT
	TRUNCATE TABLE TIMEDIM
	TRUNCATE TABLE MODELDIM
	TRUNCATE TABLE PILOTDIM
	TRUNCATE TABLE STAGING

	ALTER TABLE FACT
	ADD CONSTRAINT FK_FACT_TIMEDIM FOREIGN KEY (TIME_ID) REFERENCES TIMEDIM,
		CONSTRAINT FK_FACT_MODELDIM FOREIGN KEY (MODEL_ID) REFERENCES MODELDIM,
		CONSTRAINT FK_FACT_PILOTDIM FOREIGN KEY (PILOT_ID) REFERENCES PILOTDIM

	INSERT INTO TIMEDIM
	SELECT DISTINCT CHAR_DATE, YEAR(CHAR_DATE), MONTH(CHAR_DATE)
	FROM CHARTER

	INSERT INTO MODELDIM
	SELECT MOD_CODE, MOD_MANUFACTURER, MOD_NAME, MOD_SEATS, MOD_CHG_MILE
	FROM MODEL

	INSERT INTO PILOTDIM
	SELECT E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, P.PIL_LICENSE, P.PIL_RATINGS, P.PIL_MED_TYPE, P.PIL_MED_DATE, P.PIL_PT135_DATE
	FROM EMPLOYEE E INNER JOIN PILOT P ON E.EMP_NUM = P.EMP_NUM
	--TROUBLE HERE
	INSERT INTO STAGING(EMP_NUM, MOD_CODE, CHAR_DATE, CHAR_DISTANCE, CHAR_FUEL_GALLONS, REVENUE)
	SELECT EMP_NUM, M.MOD_CODE, C.CHAR_DATE, SUM(C.CHAR_DISTANCE) AS [DISTANCE], SUM(C.CHAR_FUEL_GALLONS) AS FUEL, SUM(M.MOD_CHG_MILE*C.CHAR_DISTANCE) AS [REVENUE]
	FROM CHARTER C CROSS JOIN  (SELECT EMP_NUM FROM PILOT P)
					CHARTER INNER JOIN AIRCRAFT A ON C.AC_NUMBER = A.AC_NUMBER
					INNER JOIN MODEL M ON A.MOD_CODE = M.MOD_CODE
	GROUP BY EMP_NUM, M.MOD_CODE, CHAR_DATE

	UPDATE STAGING
	SET TIME_ID = T.TIME_ID
	FROM STAGING S INNER JOIN TIMEDIM T ON S.CHAR_DATE = T.CHAR_DATE

	UPDATE STAGING 
	SET MODEL_ID = MD.MODEL_ID
	FROM STAGING S INNER JOIN MODELDIM MD ON S.MOD_CODE = MD.MOD_CODE

	UPDATE STAGING
	SET PILOT_ID = PD.PILOT_ID
	FROM STAGING S INNER JOIN PILOTDIM PD ON S.EMP_NUM = PD.EMP_NUM

	INSERT INTO FACT (TIME_ID, MODEL_ID, PILOT_ID, CHAR_DISTANCE, CHAR_FUEL_GALLONS, REVENUE)
	SELECT TIME_ID, MODEL_ID, PILOT_ID, CHAR_DISTANCE, CHAR_FUEL_GALLONS, REVENUE
	FROM STAGING
	 
END
GO


